apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-noticias-configmap
          volumeMounts:
            - name: sistema-noticias-imagens
              mountPath: /var/www/html/uploads
            - name: sistema-noticias-sessao
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
      volumes:
        - name: sistema-noticias-imagens
          persistentVolumeClaim:
            claimName: sistema-noticias-imagens-pvc
        - name: sistema-noticias-sessao
          persistentVolumeClaim:
            claimName: sistema-noticias-sessao-pvc
  selector:
    matchLabels:
      app: sistema-noticias
  serviceName: sistema-noticias-service
