apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
        - name: vollmed-api
          image: leonardosartorello/vollmed:v9
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dados
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: dados
                  key: DB_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: senhas
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: dados
                  key: REDIS_HOST
          livenessProbe:
            httpGet:
              path: /paciente
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
